import type { CSSProperties } from 'react';

/** Layout em cartões alinhado ao restante da Sala Pastoral (tons neutros + azul de ação). */
export const styles: Record<string, CSSProperties> = {
  wrap: {
    padding: '32px',
    maxWidth: 960,
    margin: '0 auto',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    marginBottom: 28,
    paddingBottom: 20,
    borderBottom: '2px solid #e5e7eb',
  },
  backBtn: {
    background: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '8px 14px',
    cursor: 'pointer',
    fontWeight: 600,
    color: '#374151',
  },
  titleBlock: { flex: 1 },
  h1: {
    fontSize: '1.75rem',
    fontWeight: 800,
    color: '#1f2937',
    margin: '0 0 4px 0',
  },
  subtitle: { margin: 0, color: '#6b7280', fontSize: '1rem' },
  card: {
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 12,
    padding: 24,
    marginBottom: 24,
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  cardTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#1f2937',
    margin: '0 0 12px 0',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  verseRef: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: '#3b82f6',
    marginBottom: 8,
  },
  verseText: {
    fontSize: '1.05rem',
    lineHeight: 1.65,
    color: '#374151',
    margin: 0,
  },
  searchRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  input: {
    flex: '1 1 220px',
    minWidth: 200,
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid #d1d5db',
    fontSize: '1rem',
  },
  select: {
    padding: '10px 12px',
    borderRadius: 8,
    border: '1px solid #d1d5db',
    background: '#fff',
    fontSize: '0.95rem',
  },
  primaryBtn: {
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '10px 20px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  muted: { color: '#6b7280', fontSize: '0.9rem', margin: '8px 0 0 0' },
  errorBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#b91c1c',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  infoBanner: {
    background: '#eff6ff',
    border: '1px solid #bfdbfe',
    color: '#1e40af',
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
    fontSize: '0.9rem',
    lineHeight: 1.5,
  },
  loadingBox: { color: '#6b7280', padding: '8px 0' },
  chipRow: { display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  chip: {
    background: '#eff6ff',
    color: '#1d4ed8',
    border: '1px solid #bfdbfe',
    borderRadius: 999,
    padding: '4px 12px',
    fontSize: '0.85rem',
    cursor: 'pointer',
  },
  resultList: { display: 'flex', flexDirection: 'column', gap: 12 },
  resultItem: {
    border: '1px solid #e5e7eb',
    borderRadius: 10,
    padding: 16,
    background: '#fafafa',
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
  },
  favBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 4,
    lineHeight: 1,
    color: '#9ca3af',
  },
  favBtnOn: { color: '#eab308' },
  occurrence: { fontSize: '0.85rem', color: '#6b7280', marginBottom: 8 },
  empty: { color: '#6b7280', fontStyle: 'italic' },
  booksSectionIntro: {
    margin: '0 0 16px 0',
    color: '#6b7280',
    fontSize: '0.9rem',
    lineHeight: 1.5,
  },
  booksTwoCols: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 24,
    marginTop: 4,
  },
  testamentBlock: { minWidth: 0 },
  testamentTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#1f2937',
    margin: '0 0 12px 0',
    paddingBottom: 8,
    borderBottom: '2px solid #e5e7eb',
  },
  booksGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(148px, 1fr))',
    gap: 8,
  },
  bookCell: {
    fontSize: '0.88rem',
    color: '#374151',
    padding: '8px 10px',
    background: '#f9fafb',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
    lineHeight: 1.35,
  },
  /** Célula interativa (mesmo visual + feedback de clique). */
  bookCellButton: {
    fontSize: '0.88rem',
    color: '#374151',
    padding: '8px 10px',
    background: '#f9fafb',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
    lineHeight: 1.35,
    cursor: 'pointer',
    textAlign: 'left' as const,
    width: '100%',
    transition: 'background 0.15s ease, border-color 0.15s ease',
  },
  bookCellSelected: {
    background: '#eff6ff',
    borderColor: '#93c5fd',
    boxShadow: '0 0 0 1px #3b82f6',
  },
  chapterPanel: {
    marginTop: 20,
    padding: 20,
    background: '#fafafa',
    borderRadius: 12,
    border: '1px solid #e5e7eb',
  },
  chapterPanelHeader: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid #e5e7eb',
  },
  chapterPanelTitle: {
    margin: 0,
    fontSize: '1.05rem',
    fontWeight: 700,
    color: '#1f2937',
    flex: '1 1 200px',
  },
  chapterToolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  chapterInput: {
    width: 72,
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #d1d5db',
    fontSize: '0.95rem',
  },
  chapterGoBtn: {
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  chapterCloseBtn: {
    background: 'transparent',
    color: '#6b7280',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  chapterVersesScroll: {
    maxHeight: 420,
    overflowY: 'auto' as const,
    paddingRight: 4,
  },
  bookOrder: { color: '#9ca3af', fontSize: '0.75rem', marginRight: 6, fontWeight: 600 },
};
