import type { CSSProperties } from 'react';

/** Estilos para grid de livros/capítulos e cartões de versículos (dashboard / leitura). */
export const bibleStyles: Record<string, CSSProperties> = {
  pageWrap: {
    padding: '24px 32px 40px',
    maxWidth: 960,
    margin: '0 auto',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
    paddingBottom: 20,
    borderBottom: '2px solid #e5e7eb',
    flexWrap: 'wrap',
  },
  backBtn: {
    background: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '8px 14px',
    cursor: 'pointer',
    fontWeight: 600,
    color: '#374151',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  titleBlock: { flex: '1 1 200px' },
  h1: {
    fontSize: '1.75rem',
    fontWeight: 800,
    color: '#1f2937',
    margin: '0 0 4px 0',
  },
  subtitle: { margin: 0, color: '#6b7280', fontSize: '1rem' },
  card: {
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 12,
    padding: 24,
    marginBottom: 24,
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#1f2937',
    margin: '0 0 16px 0',
  },
  booksTwoCols: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 24,
  },
  testamentBlock: { minWidth: 0 },
  testamentTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#1f2937',
    margin: '0 0 12px 0',
    paddingBottom: 8,
    borderBottom: '2px solid #e5e7eb',
  },
  booksGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(148px, 1fr))',
    gap: 10,
  },
  bookCard: {
    fontSize: '0.88rem',
    color: '#374151',
    padding: '12px 14px',
    background: '#f9fafb',
    borderRadius: 10,
    border: '1px solid #e5e7eb',
    lineHeight: 1.35,
    cursor: 'pointer',
    textAlign: 'left' as const,
    width: '100%',
    transition: 'background 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease',
  },
  bookCardHover: {
    background: '#fff',
    borderColor: '#93c5fd',
    boxShadow: '0 2px 8px rgba(59, 130, 246, 0.12)',
  },
  bookOrder: { color: '#9ca3af', fontSize: '0.75rem', marginRight: 6, fontWeight: 600 },
  chaptersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(72px, 1fr))',
    gap: 10,
    maxWidth: '100%',
  },
  chapterCell: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 4,
    padding: '8px 6px',
    minHeight: 76,
    fontWeight: 700,
    fontSize: '0.95rem',
    color: '#1e40af',
    background: '#eff6ff',
    border: '1px solid #bfdbfe',
    borderRadius: 10,
    cursor: 'pointer',
    transition: 'background 0.15s ease, border-color 0.15s ease, transform 0.1s ease',
  },
  chapterCellNumber: {
    textAlign: 'center' as const,
    lineHeight: 1.1,
  },
  chapterProgressTrack: {
    width: '100%',
    height: 5,
    borderRadius: 4,
    background: 'rgba(148, 163, 184, 0.45)',
    overflow: 'hidden',
  },
  chapterProgressFill: {
    height: '100%',
    borderRadius: 4,
    background: 'linear-gradient(90deg, #22c55e, #4ade80)',
    transition: 'width 0.2s ease',
  },
  chapterFractionLabel: {
    fontSize: '0.62rem',
    fontWeight: 600,
    textAlign: 'center' as const,
    color: '#64748b',
    lineHeight: 1.1,
  },
  chapterCellHover: {
    background: '#dbeafe',
    transform: 'scale(1.03)',
  },
  /** Leitura iniciada, capítulo ainda não completo. */
  chapterCellPartial: {
    background: '#fffbeb',
    borderColor: '#fcd34d',
    color: '#92400e',
  },
  /** Todos os versículos do capítulo marcados como lidos. */
  chapterCellHasReads: {
    background: '#ecfdf5',
    borderColor: '#34d399',
    color: '#047857',
    boxShadow: 'inset 0 0 0 2px rgba(16, 185, 129, 0.35)',
  },
  versesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  verseCard: {
    border: '1px solid #e5e7eb',
    borderRadius: 10,
    padding: '14px 16px',
    background: '#fafafa',
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
  },
  /** Versículo marcado como lido (persistido no servidor). */
  verseCardRead: {
    background: '#f0fdf4',
    borderColor: '#86efac',
    boxShadow: 'inset 0 0 0 1px rgba(22, 163, 74, 0.12)',
  },
  readToggleBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 4,
    lineHeight: 1,
    color: '#9ca3af',
    flexShrink: 0,
  },
  readToggleBtnOn: {
    color: '#16a34a',
  },
  verseNum: {
    flexShrink: 0,
    minWidth: 36,
    height: 36,
    borderRadius: 8,
    background: '#3b82f6',
    color: '#fff',
    fontWeight: 800,
    fontSize: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verseText: {
    fontSize: '1.05rem',
    lineHeight: 1.65,
    color: '#374151',
    margin: 0,
    flex: 1,
  },
  muted: { color: '#6b7280', fontSize: '0.9rem' },
  errorBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#b91c1c',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  loadingBox: { color: '#6b7280', padding: '16px 0', display: 'flex', alignItems: 'center', gap: 10 },
  favBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 4,
    lineHeight: 1,
    color: '#9ca3af',
    flexShrink: 0,
  },
  favBtnOn: { color: '#eab308' },
  /** Botão flutuante: voltar ao topo da área de leitura (scroll em `.app-content`). */
  scrollToTopFab: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    zIndex: 100,
    width: 48,
    height: 48,
    borderRadius: '50%',
    border: '1px solid #bfdbfe',
    background: '#3b82f6',
    color: '#fff',
    boxShadow: '0 4px 14px rgba(37, 99, 235, 0.45)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
  },
};
